### ISSUE TITLE
Error: Failed to read the given file as a state or plan file

### ISSUE THREAD

**Issue by PrestonR** [JaydenMaalouf/azure-pipelines-terraform-output#12]
I tried using the standard plan file, and the JSON file, either way, I get a complaint about the "version" missing. Confused because the documentation doesn't say anything about converting the binary output file to JSON before parsing it - or maybe it's failing it's own internal JSON parsing because of the version mismatch? I use `tfenv` in the pipeline to set the version for whatever the workspace is using - in this case my workspace is using 1.5.5, but it looks like the task is defaulting to whatever the latest version is.

Assuming it's just a version issue, is there a way to force the task to use a specific version? Or somehow allow it to be dynamic enough to read the currently used terraform version? I'm using the `-chdir` flag to hot swap workspaces within the pipeline, which, incidentally is the same as the below parameter: `${{ parameters.workspace }}`

```
  - task: TerraformOutput@1
    displayName: Terraform Show
    inputs:
      outputFilePath: $(Build.ArtifactStagingDirectory)/output.tfplan
      artifactName: ${{ parameters.workspace }}
```

```
Starting: Terraform Show
==============================================================================
Task         : Terraform Load Output
Description  : Load Terraform Output into Terraform Tab
Version      : 1.1.34
Author       : Jayden Maalouf
Help         : 
==============================================================================
##[error]Terraform Output failed with Exit Code: 1
      Error Message: ╷
│ Error: Failed to read the given file as a state or plan file
│ 
│ State read error: Error reading /agent/_work/1/a/output.tfplan as a
│ statefile: 2 problems:
│ 
│ - Unsupported state file format: The state file could not be parsed as
│ JSON: syntax error at byte offset 1.
│ - Unsupported state file format: The state file does not have a "version"
│ attribute, which is required to identify the format version.
│ 
│ Plan read error: plan file was created by Terraform 1.5.5, but this is
│ 1.5.7; plan files cannot be transferred between different Terraform
│ versions
╵
```

**Comment by JaydenMaalouf** [comment]
Try running the Terraform installer (available in the [Microsoft Terraform extension](https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks)) before executing the Terraform Show task

```yaml
steps:
  - task: TerraformInstaller@0
    displayName: Install Terraform v1.5.7
    inputs:
      terraformVersion: 1.5.7
  - task: TerraformOutput@1
    ...
```
