### ISSUE TITLE
Is it possible to add multiple TFPlan with 1 task ?

### ISSUE THREAD

**Issue by ultrajericho** [JaydenMaalouf/azure-pipelines-terraform-output#7]
Hello,

I am creating multiple TFPlan thoughout my Azure DevOps Releases and I would like to know if it would be possible to load every tfplan with a single task from you ?

My TFPlans are created dynamically but I can't duplicate dynamically your task.

So I want to know if it would be possible to add something like that with "*" selector : 

- task: TerraformOutput@1
  inputs:
    **outputFilePath: *.tfplan**
    artifactName: Staging

Regards,

Alex.

**Comment by JaydenMaalouf** [comment]
Is there a reason you're unable to duplicate the task?
You should be able to reuse the task by giving each use of it a unique name
For example:
```yaml
steps:
  - task: TerraformOutput@1
    name: staging
    inputs:
      outputFilePath: staging.tfplan
      artifactName: Staging
  - task: TerraformOutput@1
    name: production
    inputs:
      outputFilePath: production.tfplan
      artifactName: Production
```

**Comment by JaydenMaalouf** [comment]
> My TFPlans are created dynamically but I can't duplicate dynamically your task.

I didn't read this part properly!
I can look at changing the input to a glob pattern to support this

**Comment by ultrajericho** [comment]
There's no problem duplicating the task. 

But in my case I run my TF Plan commands in a "for each" inside a Powershell script.

Sometimes there may be 10 TF Plans (each with its own output), sometimes there may be only 1 or 2.
Unfortunately, I can't write the number of "Terraform Output" tasks in advance, as I'd like something dynamic.

So I was wondering if with something like regexes or just the all "*" operators, it would be possible to load several TFplans at once in the same task (and possibly create a line for each of them in the dropdown of your "Terraform Plan" tab.

By the way, I've been using your extension a lot since it started working with Release. It's very practical and useful!

**Comment by JaydenMaalouf** [comment]
This feature is now available as part of #9 
You can update your task to use the following `useGlobPattern` like so:

```yaml
- task: TerraformOutput@1
  inputs:
    useGlobPattern: true
```

And can override the default pattern of `**/*.tfplan` by changing the `outputFilePattern` input variable

**Comment by ultrajericho** [comment]
Hello @JaydenMaalouf ,

Thanks for you update on this extension.

Unfortunately, I'm running into a problem: despite the fact that I'm indicating a pattern leading to several existing paths, it seems that your extension is returning an error.

![image](https://github.com/JaydenMaalouf/azure-pipelines-terraform-output/assets/74764876/d89dffee-86c7-4b6c-a455-18988d6fca15)


![image](https://github.com/JaydenMaalouf/azure-pipelines-terraform-output/assets/74764876/91784aca-eb59-4b31-803d-7b5ffb30cb0e)



On the other hand, what surprises me is that I have 3 possible folders with this pattern and the extension returns an error as soon as it doesn't find the first path. Shouldn't it continue and test on all existing paths instead of stopping at the first one?

**Comment by ultrajericho** [comment]
Hello again @JaydenMaalouf ,
 
I also tried by specifying a "searchDirectory" but it didn't work better

![image](https://github.com/JaydenMaalouf/azure-pipelines-terraform-output/assets/74764876/e62e67a6-57bf-466f-b957-910d0c6bf97c)

The weird thing is that is find the file using the pattern because in the console it managed to replace my pattern "_PRStrategy_Artifacts\PrDeployFiles\**\*.tfplan" by "_PRStrategy_Artifacts\PrDeployFiles\PrDeployResource-0_sub-cep-staging-extend1_kv-devops-stg03\kv-devops-stg03.tfplan:"  but it persists with the statefile error and the plan read error.

**Comment by JaydenMaalouf** [comment]
Hmm, what does the folder/file structure look like?

The tfplan should be in the same directory as the Terraform files/modules to ensure it is able to validate the state

If you can, provide a tree of the directory and send me through the log. Don't forget to mask any sensitive filenames

**Comment by ultrajericho** [comment]
Hello @JaydenMaalouf ,

Thanks for your answer, so for this task input :
![image](https://github.com/JaydenMaalouf/azure-pipelines-terraform-output/assets/74764876/3dd00f0c-8c55-417d-ba35-a95a50993c1c)

I get this console log :
![image](https://github.com/JaydenMaalouf/azure-pipelines-terraform-output/assets/74764876/53519f24-1088-4ae2-b6f9-4e1d3e4c1cfd)

And the folder looks like this  (you can see the path in the file explorer) : 

![image](https://github.com/JaydenMaalouf/azure-pipelines-terraform-output/assets/74764876/5e74583b-c43a-41d6-9d10-4adaa54d18a5)

**EDIT :** The full artifact :

![image](https://github.com/JaydenMaalouf/azure-pipelines-terraform-output/assets/74764876/b32b8702-743a-42c6-b2ed-06aac90e23c0)

**Comment by JaydenMaalouf** [comment]
Can you try setting the parameters like so to see if it works?

```yaml
- task: TerraformOutput@1
  inputs:
    useGlobPattern: true
    searchDirectory: $(System.ArtifactsDirectory)/_PRStrategy_Artifacts/PrDeployFiles
```

**Comment by ultrajericho** [comment]
Without the pattern "**/*.tfplan" ?

Because I already tried 

```
- task: TerraformOutput@1
  inputs:
    useGlobPattern: true
    searchDirectory: $(System.ArtifactsDirectory)/_PRStrategy_Artifacts/PrDeployFiles/**/*.tfplan

```
and I had the same result ^^

**Comment by JaydenMaalouf** [comment]
> Without the pattern "**/*.tfplan" ?
> 
> Because I already tried 
> 
> ```
> - task: TerraformOutput@1
>   inputs:
>     useGlobPattern: true
>     searchDirectory: $(System.ArtifactsDirectory)/_PRStrategy_Artifacts/PrDeployFiles/**/*.tfplan
> 
> ```
> and I had the same result ^^ 

Yes, without the `**/*.tfplan`. It will default to this if it isn't passed in

**Comment by ultrajericho** [comment]
Hello @JaydenMaalouf 

I tried with this : 
```
- task: TerraformOutput@1
  inputs:
    useGlobPattern: true
    searchDirectory: $(System.ArtifactsDirectory)/_PRStrategy_Artifacts/PrDeployFiles
```

And I got this error :

![image](https://github.com/JaydenMaalouf/azure-pipelines-terraform-output/assets/74764876/c868dcaa-5339-46b7-9c5b-044e0fb89e9a)

In fact it looks even worse as it doesn't seems to write the right path like when I used "**/*.tfplan".

**Comment by brad2190** [comment]
I have been testing with this today, with similar results, it as though it is detecting the plan but not setting the working directory to the folder holding the .tfplan and therefore failing.

In the case where its a single Terraform composition it works but in my case I have a structure like below:

- /composition1
.terraform
out.tfplan
main.tf
- /composition2
...

Task settings are
useGlobalPattern: true
search directory: "$(Build.SourcesDirectory)/output/"

Under output is the above composition directories.

**Comment by JaydenMaalouf** [comment]
@ultrajericho @brad2190 
I've just pushed a fix as part of [#1a73972f5872ccc070fe2390469782f43229a229](https://github.com/JaydenMaalouf/azure-pipelines-terraform-output/commit/1a73972f5872ccc070fe2390469782f43229a229) (version 1.1.53)
Let me know if this works for you both

**Comment by brad2190** [comment]
I can confirm this is now working as expected. @JaydenMaalouf

**Comment by ultrajericho** [comment]
Hello @JaydenMaalouf ,

Thanks for the fix.
Now it works with this configuration : 

```
- task: JaydenMaalouf.terraform-output.TerraformOutput.TerraformOutput@1
  displayName: 'Terraform Load Output'
  inputs:
    useGlobPattern: true
    searchDirectory: '$(System.ArtifactsDirectory)/_PRStrategy_Artifacts/PrDeployFiles'
```
